## Builder
# STAGE 1: building the executable.

FROM golang:1.16-alpine3.15 AS builder

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o main && chmod +x main


## Deploy
# STAGE 2: build the container to run.

FROM alpine:3.15 AS deploy

WORKDIR /

COPY --from=builder /app/main /

EXPOSE 80

ENTRYPOINT [ "./main" ]
